name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
  release:
    types:
      - published
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cbl-migrator
        shell: bash -l {0}
        run: pip install -e . pytest twine

      - name: Run tests
        shell: bash -l {0}
        run: pytest

      - name: Build wheels
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_all:
    name: Upload if release
    needs: [build]
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
